-- CreateEnum
CREATE TYPE "PROVIDER" AS ENUM ('MANUAL', 'GOOGLE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "provider" "PROVIDER" NOT NULL DEFAULT 'MANUAL',
ALTER COLUMN "password" DROP NOT NULL;
